# Generated by Django 5.1 on 2024-09-07 04:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_authentication', '0005_alter_industry_name_alter_location_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='avatar_images/')),
                ('company_name', models.CharField(help_text='Enter your company name', max_length=255)),
                ('business_type', models.CharField(help_text='Enter business type', max_length=100)),
                ('company_stage', models.CharField(help_text='Enter current company stage', max_length=100)),
                ('listed_status', models.BooleanField(default=False, help_text='Activate / Deactivate')),
                ('company_description', models.TextField(help_text='Describe your company (250 words or more)', max_length=1000)),
                ('seeking_amount', models.DecimalField(decimal_places=2, help_text='Enter amount seeking', max_digits=15)),
                ('website', models.URLField(help_text='Enter website URL', validators=[django.core.validators.URLValidator()])),
                ('product_type', models.CharField(help_text='Enter product type', max_length=100)),
                ('annual_revenue', models.DecimalField(decimal_places=2, help_text='Enter annual revenue', max_digits=15)),
                ('employee_count', models.PositiveIntegerField(help_text='Enter employee count')),
                ('social_media_links', models.JSONField(default=dict, help_text='Social media links (LinkedIn, Facebook, Twitter)')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_authentication.industry')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_authentication.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(help_text='Enter document title', max_length=255)),
                ('document_description', models.TextField(help_text='Enter document description')),
                ('document_file', models.FileField(help_text='Choose File', upload_to='business_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(help_text='Enter video title', max_length=255)),
                ('video_description', models.TextField(help_text='Enter video description')),
                ('video_file', models.FileField(help_text='Upload Video', upload_to='business_video_pitches/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_pitches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
