# Generated by Django 5.1 on 2024-09-10 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_documentsbusiness_user_alter_videopitch_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspreferences',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='businesspreferences',
            name='facebook',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='businesspreferences',
            name='linkedIn',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='businesspreferences',
            name='twitter',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
