# Generated by Django 5.1.2 on 2024-10-29 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_documentsbusiness_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentsbusiness',
            unique_together={('user', 'document_title')},
        ),
    ]
