# Generated by Django 5.1 on 2024-08-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('investor', 'Investor'), ('business', 'Business'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
