# Generated by Django 5.1 on 2024-08-27 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='avatar_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('preferred_industries', models.ManyToManyField(blank=True, to='user_authentication.industry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_preferences', to=settings.AUTH_USER_MODEL)),
                ('preferred_locations', models.ManyToManyField(blank=True, to='user_authentication.location')),
            ],
        ),
    ]
