# Generated by Django 5.1.2 on 2024-11-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='trial_ends_at',
        ),
    ]
