# Generated by Django 5.1.2 on 2024-11-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_subscriptions_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['-created_at']},
        ),
    ]
